# Site settings
title: Yue Feng
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yue Feng
user_description: A computer vision PhD student working with Prof. Jia-Bin Huang at University of Maryland, College Park.
user_title: Computer Vision PhD student
email: yuefeng@umd.edu
twitter_username: Yue_Feng21
# instagram_username: luckyluckyangel_yf
# facebook_username: Yue Feng
linkedin_username: YueFeng
github_username:  yuefeng21
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
